const { Country } = require("../Modal/countryModal");

const countryList = [
  new Country("AED", "AE", "United Arab Emirates"),
  new Country("AFN", "AF", "Afghanistan"),
  new Country("XCD", "AG", "Antigua and Barbuda"),
  new Country("ALL", "AL", "Albania"),
  new Country("AMD", "AM", "Armenia"),
  new Country("ANG", "AN", "Netherlands Antilles"),
  new Country("AOA", "AO", "Angola"),
  new Country("AQD", "AQ", "Antarctica"),
  new Country("ARS", "AR", "Argentina"),
  new Country("AUD", "AU", "Australia"),
  new Country("AZN", "AZ", "Azerbaijan"),
  new Country("BAM", "BA", "Bosnia and Herzegovina"),
  new Country("BBD", "BB", "Barbados"),
  new Country("BDT", "BD", "Bangladesh"),
  new Country("XOF", "BE", "Belgium"),
  new Country("BGN", "BG", "Bulgaria"),
  new Country("BHD", "BH", "Bahrain"),
  new Country("BIF", "BI", "Burundi"),
  new Country("BMD", "BM", "Bermuda"),
  new Country("BND", "BN", "Brunei"),
  new Country("BOB", "BO", "Bolivia"),
  new Country("BRL", "BR", "Brazil"),
  new Country("BSD", "BS", "Bahamas"),
  new Country("NOK", "BV", "Bouvet Island"),
  new Country("BWP", "BW", "Botswana"),
  new Country("BYR", "BY", "Belarus"),
  new Country("BZD", "BZ", "Belize"),
  new Country("CAD", "CA", "Canada"),
  new Country("CDF", "CD", "Democratic Republic of the Congo"),
  new Country("XAF", "CF", "Central African Republic"),
  new Country("CHF", "CH", "Switzerland"),
  new Country("CLP", "CL", "Chile"),
  new Country("CNY", "CN", "China"),
  new Country("COP", "CO", "Colombia"),
  new Country("CRC", "CR", "Costa Rica"),
  new Country("CUP", "CU", "Cuba"),
  new Country("CVE", "CV", "Cape Verde"),
  new Country("CYP", "CY", "Cyprus"),
  new Country("CZK", "CZ", "Czech Republic"),
  new Country("DJF", "DJ", "Djibouti"),
  new Country("DKK", "DK", "Denmark"),
  new Country("DOP", "DO", "Dominican Republic"),
  new Country("DZD", "DZ", "Algeria"),
  new Country("ECS", "EC", "Ecuador"),
  new Country("EEK", "EE", "Estonia"),
  new Country("EGP", "EG", "Egypt"),
  new Country("ETB", "ET", "Ethiopia"),
  new Country("EUR", "FR", "France"),
  new Country("FJD", "FJ", "Fiji"),
  new Country("FKP", "FK", "Falkland Islands"),
  new Country("GBP", "GB", "United Kingdom"),
  new Country("GEL", "GE", "Georgia"),
  new Country("GGP", "GG", "Guernsey"),
  new Country("GHS", "GH", "Ghana"),
  new Country("GIP", "GI", "Gibraltar"),
  new Country("GMD", "GM", "Gambia"),
  new Country("GNF", "GN", "Guinea"),
  new Country("GTQ", "GT", "Guatemala"),
  new Country("GYD", "GY", "Guyana"),
  new Country("HKD", "HK", "Hong Kong"),
  new Country("HNL", "HN", "Honduras"),
  new Country("HRK", "HR", "Croatia"),
  new Country("HTG", "HT", "Haiti"),
  new Country("HUF", "HU", "Hungary"),
  new Country("IDR", "ID", "Indonesia"),
  new Country("ILS", "IL", "Israel"),
  new Country("INR", "IN", "India"),
  new Country("IQD", "IQ", "Iraq"),
  new Country("IRR", "IR", "Iran"),
  new Country("ISK", "IS", "Iceland"),
  new Country("JMD", "JM", "Jamaica"),
  new Country("JOD", "JO", "Jordan"),
  new Country("JPY", "JP", "Japan"),
  new Country("KES", "KE", "Kenya"),
  new Country("KGS", "KG", "Kyrgyzstan"),
  new Country("KHR", "KH", "Cambodia"),
  new Country("KMF", "KM", "Comoros"),
  new Country("KPW", "KP", "North Korea"),
  new Country("KRW", "KR", "South Korea"),
  new Country("KWD", "KW", "Kuwait"),
  new Country("KYD", "KY", "Cayman Islands"),
  new Country("KZT", "KZ", "Kazakhstan"),
  new Country("LAK", "LA", "Laos"),
  new Country("LBP", "LB", "Lebanon"),
  new Country("LKR", "LK", "Sri Lanka"),
  new Country("LRD", "LR", "Liberia"),
  new Country("LSL", "LS", "Lesotho"),
  new Country("LTL", "LT", "Lithuania"),
  new Country("LVL", "LV", "Latvia"),
  new Country("LYD", "LY", "Libya"),
  new Country("MAD", "MA", "Morocco"),
  new Country("MDL", "MD", "Moldova"),
  new Country("MGA", "MG", "Madagascar"),
  new Country("MKD", "MK", "North Macedonia"),
  new Country("MMK", "MM", "Myanmar"),
  new Country("MNT", "MN", "Mongolia"),
  new Country("MOP", "MO", "Macau"),
  new Country("MRO", "MR", "Mauritania"),
  new Country("MTL", "MT", "Malta"),
  new Country("MUR", "MU", "Mauritius"),
  new Country("MVR", "MV", "Maldives"),
  new Country("MWK", "MW", "Malawi"),
  new Country("MXN", "MX", "Mexico"),
  new Country("MYR", "MY", "Malaysia"),
  new Country("MZN", "MZ", "Mozambique"),
  new Country("NAD", "NA", "Namibia"),
  new Country("XPF", "NC", "New Caledonia"),
  new Country("NGN", "NG", "Nigeria"),
  new Country("NIO", "NI", "Nicaragua"),
  new Country("NPR", "NP", "Nepal"),
  new Country("NZD", "NZ", "New Zealand"),
  new Country("OMR", "OM", "Oman"),
  new Country("PAB", "PA", "Panama"),
  new Country("PEN", "PE", "Peru"),
  new Country("PGK", "PG", "Papua New Guinea"),
  new Country("PHP", "PH", "Philippines"),
  new Country("PKR", "PK", "Pakistan"),
  new Country("PLN", "PL", "Poland"),
  new Country("PYG", "PY", "Paraguay"),
  new Country("QAR", "QA", "Qatar"),
  new Country("RON", "RO", "Romania"),
  new Country("RSD", "RS", "Serbia"),
  new Country("RUB", "RU", "Russia"),
  new Country("RWF", "RW", "Rwanda"),
  new Country("SAR", "SA", "Saudi Arabia"),
  new Country("SBD", "SB", "Solomon Islands"),
  new Country("SCR", "SC", "Seychelles"),
  new Country("SDG", "SD", "Sudan"),
  new Country("SEK", "SE", "Sweden"),
  new Country("SGD", "SG", "Singapore"),
  new Country("SKK", "SK", "Slovakia"),
  new Country("SLL", "SL", "Sierra Leone"),
  new Country("SOS", "SO", "Somalia"),
  new Country("SRD", "SR", "Suriname"),
  new Country("STD", "ST", "São Tomé and Príncipe"),
  new Country("SVC", "SV", "El Salvador"),
  new Country("SYP", "SY", "Syria"),
  new Country("SZL", "SZ", "Eswatini"),
  new Country("THB", "TH", "Thailand"),
  new Country("TJS", "TJ", "Tajikistan"),
  new Country("TMT", "TM", "Turkmenistan"),
  new Country("TND", "TN", "Tunisia"),
  new Country("TOP", "TO", "Tonga"),
  new Country("TRY", "TR", "Turkey"),
  new Country("TTD", "TT", "Trinidad and Tobago"),
  new Country("TWD", "TW", "Taiwan"),
  new Country("TZS", "TZ", "Tanzania"),
  new Country("UAH", "UA", "Ukraine"),
  new Country("UGX", "UG", "Uganda"),
  new Country("USD", "US", "United States"),
  new Country("UYU", "UY", "Uruguay"),
  new Country("UZS", "UZ", "Uzbekistan"),
  new Country("VEF", "VE", "Venezuela"),
  new Country("VND", "VN", "Vietnam"),
  new Country("VUV", "VU", "Vanuatu"),
  new Country("YER", "YE", "Yemen"),
  new Country("ZAR", "ZA", "South Africa"),
  new Country("ZMK", "ZM", "Zambia"),
  new Country("ZWD", "ZW", "Zimbabwe"),
];



export default countryList;
